### ISSUE TITLE
확장프로그램 즉시 공유 요청

### ISSUE THREAD

**Issue by imeugeneco** [sunday-funday/aigorithm#1]
좋은 건 좀 같이 사용합시다!!

**Comment by CodeJuggler19** [comment]
Chrome에 있는 확장 프로그램 "백준허브"입니다. 아주 깜찍한 녀석이구요.
이미 알고 계실 수도 있지만 공유하겠습니다. ~ 
https://oliviakim.tistory.com/34

**Comment by imeugeneco** [comment]
굿보이
